{
    'name': "TMC SICON",
    'version': '13.0.1.0.0',
    'summary': 'Sistema de Concesiones Generales',
    'author': 'Tribunal Municipal de Cuentas - Municipalidad de Rosario',
    'website': 'https://www.tmcrosario.gob.ar',
    'license': 'AGPL-3',
    'depends': [
        # 'report_py3o',
        # 'report_py3o_fusion_server',
        'tmc',
        'tmc_data',
        'document_pdf',
        'partner_tmc',
        'partner_fiscal',
        'municipal',
        'partner_municipal',
        # 'partner_external_map '
    ],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'views/sicon_menus.xml',
        'views/highlight_views.xml',
        'views/concession_views.xml',
        'views/concession_menus.xml',
        'views/event_views.xml',
        'views/event_menus.xml',
        'views/event_type_views.xml',
        'views/event_type_menus.xml',
        'views/partner_views.xml',
        'views/partner_menus.xml',
        'report/unrelated_documents.xml',
        # 'report/concessions_listing.xml',
        # 'report/concession.xml',
        'wizards/add_event_views.xml',
        'wizards/concession_report_views.xml'
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'qweb': []
}  # yapf: disable
